site_name: LAB's Cr0wth
site_description: Cours de STI2D
site_author: Christopher CHAMAND

docs_dir: docs

nav:
- "<img src='https://fabricenativel.github.io/icones/home.svg' width=16px height=16px>&thinsp; Accueil" :
    - index.md
- "<img src='https://fabricenativel.github.io/icones/checklist-16.svg' width=16px height=16px>&thinsp; STI2D_I2D" :
      - "Index" : STI2D/i2d.md
- "<img src='https://fabricenativel.github.io/icones/checklist-16.svg' width=16px height=16px>&thinsp; STI2D_2I2D" :
      - "Index" : STI2D/2i2d.md
- "<img src='https://fabricenativel.github.io/icones/checklist-16.svg' width=16px height=16px>&thinsp; STI2D_SIN" :
      - "Index" : STI2D/sin.md
- "<img src='https://fabricenativel.github.io/icones/checklist-16.svg' width=16px height=16px>&thinsp; STI2D_AC" :
      - "Index" : STI2D/ac.md
- "<img src='https://fabricenativel.github.io/icones/file-badge-16.svg' width=16px height=16px>&thinsp; STI2D_Documents_officiels" :
    - "Index" : STI2D/officiels.md
- "<img src='https://fabricenativel.github.io/icones/graduation-cap.svg' width=16px height=16px>&thinsp; Annales du Bac" :
    - index_annales.md
    - '2021': 
      - "Epreuves écrites" : Terminale/Annales/2021/EE.md
      - "Epreuves pratiques" : Terminale/Annales/2021/EP.md
    - '2022': 
      - "Epreuves écrites" : Terminale/Annales/2022/EE.md
      - "Epreuves pratiques" : Terminale/Annales/2022/EP.md
- "<img src='https://fabricenativel.github.io/icones/lightbulb.svg' width=16px height=16px>&thinsp; Projets" :
    - projets.md
    - "Projets de Première" : projets_prem.md
    - "Projets de Terminale" : projets_term.md
- "<img src='https://fabricenativel.github.io/icones/links.svg' width=16px height=16px>&thinsp; Liens" :
    - liens.md
- "<img src='https://fabricenativel.github.io/icones/python.svg' width=16px height=16px>&thinsp; Python" :
    - python.md
- "<img src='https://fabricenativel.github.io/icones/information.svg' width=16px height=16px>&thinsp; A propos" :
    - apropos.md          

theme:
  favicon: images/favicon.ico
  icon:
    logo: fontawesome/solid/dragon
  
  name: material
  language: fr

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Darkmode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Lightmode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cr0wth/

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
    # Exception pour code highlight (de façon à faire fonctionner mermaid)
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true          # Volets glissants.  === "Mon volet"
  - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
  - pymdownx.keys:
      strict: false


  - footnotes
  - attr_list
  # Permet l'utilisation d'abbréviation dans le fichier syntaxe *[abbr]: description (voir glossaire.md)
  - abbr
  # Permet l'insertion de fichiers dans le document à l'aide de la syntaxe --8<-- "includes/glossaire.md"
  - pymdownx.snippets
  # Admonitions et variantes (details : repliable, superfences : avec onglet)
  - admonition

plugins:
  - search
#  - macros

copyright: |
  &copy; 2023 <a href="" target="_blank" rel="noopener">Christopher CHAMAND</a>